import { JobType, LocationType, JobStatus } from "@prisma/client";

export const jobsData = [
  {
    titleEnglish: "Software Engineer",
    titleQanjobal: "Ingeniero de Software",
    companyName: "Tech Solutions Inc.",
    businessContactEmail: "hiring@techsolutions.com",
    jobType: JobType.FULLTIME,
    acceptedLanguages: ["Non-English", "Spanish"],
    locationType: LocationType.HYBRID,
    city: "San Francisco",
    state: "California",
    url: "https://techsolutions.com/jobs/software-engineer-1",
    salary: 120000,
    expirationDate: new Date("2025-12-31"),
    descriptionEnglish:
      "We are looking for a talented software engineer to join our team. Experience with React and Node.js required.",
    descriptionQanjobal:
      "Kaẍi q'omal jun ingeniero de software yul ka department. K'ulal yul React yet' Node.js.",
    status: JobStatus.ACTIVE,
  },
  {
    titleEnglish: "Restaurant Server",
    titleQanjobal: "Mesero/a de Restaurante",
    companyName: "The Golden Plate",
    businessContactEmail: "jobs@goldenplate.com",
    jobType: JobType.PARTTIME,
    acceptedLanguages: ["Non-English", "Spanish", "Q'anjob'al"],
    locationType: LocationType.INPERSON,
    city: "Los Angeles",
    state: "California",
    url: "https://goldenplate.com/careers/server",
    salary: 35000,
    expirationDate: new Date("2025-06-30"),
    descriptionEnglish:
      "Join our friendly team as a part-time server. No experience necessary, we will train. Bilingual speakers encouraged to apply.",
    descriptionQanjobal:
      "Chex yul ka equipo. Man k'ulal mulnaj, oj ka colonab'il. K'ulal yul kab' k'anel.",
    status: JobStatus.ACTIVE,
  },
  {
    titleEnglish: "Construction Worker",
    titleQanjobal: "Trabajador de Construcción",
    companyName: "Metro Builders LLC",
    businessContactEmail: "careers@metrobuilders.com",
    jobType: JobType.FULLTIME,
    acceptedLanguages: ["Non-English", "Spanish", "Q'anjob'al"],
    locationType: LocationType.INPERSON,
    city: "Austin",
    state: "Texas",
    url: "https://metrobuilders.com/jobs/construction-worker",
    salary: 45000,
    expirationDate: new Date("2025-08-15"),
    descriptionEnglish:
      "Seeking experienced construction workers for residential projects. Must be able to work outdoors and lift heavy materials.",
    descriptionQanjobal:
      "Kaẍi q'omal trabajadores yet' construcción. K'ulal mulnaj yul construcción.",
    status: JobStatus.ACTIVE,
  },
  {
    titleEnglish: "Data Entry Clerk",
    titleQanjobal: "Oficinista de Entrada de Datos",
    companyName: "AdminPro Services",
    businessContactEmail: "hr@adminpro.com",
    jobType: JobType.TEMPORARY,
    acceptedLanguages: ["Non-English"],
    locationType: LocationType.REMOTE,
    city: "New York",
    state: "New York",
    url: "https://adminpro.com/jobs/data-entry-temp",
    salary: 38000,
    expirationDate: new Date("2025-05-01"),
    descriptionEnglish:
      "Temporary position for data entry work. 3-month contract with possibility of extension. Work from home.",
    descriptionQanjobal:
      "Mulnaj temporal yet' entrada de datos. 3 mes yet' contrato.",
    status: JobStatus.ARCHIVED,
  },
  {
    titleEnglish: "Marketing Intern",
    titleQanjobal: "Practicante de Marketing",
    companyName: "Bright Future Marketing",
    businessContactEmail: "internships@brightfuture.com",
    jobType: JobType.INTERNSHIP,
    acceptedLanguages: ["Non-English", "Spanish"],
    locationType: LocationType.HYBRID,
    city: "Chicago",
    state: "Illinois",
    url: "https://brightfuture.com/careers/marketing-intern",
    salary: 25000,
    expirationDate: new Date("2025-09-30"),
    descriptionEnglish:
      "Paid internship opportunity for students interested in digital marketing. Flexible schedule.",
    descriptionQanjobal:
      "Oportunidad yet' práctica yet' estudiantes. Horario flexible.",
    status: JobStatus.ACTIVE,
  },
  {
    titleEnglish: "Freelance Graphic Designer",
    titleQanjobal: "Diseñador Gráfico Independiente",
    companyName: "Creative Studio Co.",
    businessContactEmail: "projects@creativestudio.com",
    jobType: JobType.FREELANCE,
    acceptedLanguages: ["Non-English"],
    locationType: LocationType.REMOTE,
    city: "Seattle",
    state: "Washington",
    url: "https://creativestudio.com/freelance/graphic-designer",
    salary: 60000,
    expirationDate: new Date("2025-07-20"),
    descriptionEnglish:
      "Looking for talented freelance graphic designers for ongoing projects. Portfolio required.",
    descriptionQanjobal:
      "Kaẍi diseñadores gráficos yet' proyectos. Portfolio k'ulal.",
    status: JobStatus.ACTIVE,
  },
  {
    titleEnglish: "Warehouse Associate",
    titleQanjobal: "Asociado de Almacén",
    companyName: "QuickShip Logistics",
    businessContactEmail: "jobs@quickship.com",
    jobType: JobType.SEASONAL,
    acceptedLanguages: ["Non-English", "Spanish", "Q'anjob'al"],
    locationType: LocationType.INPERSON,
    city: "Phoenix",
    state: "Arizona",
    url: "https://quickship.com/jobs/warehouse-seasonal",
    salary: 32000,
    expirationDate: new Date("2025-12-25"),
    descriptionEnglish:
      "Seasonal warehouse position for holiday season. Training provided. Evening and weekend shifts available.",
    descriptionQanjobal:
      "Mulnaj temporal yet' almacén. Oj ka colonab'il. Turnos yet' noche yet' fin de semana.",
    status: JobStatus.ARCHIVED,
  },
  {
    titleEnglish: "Customer Service Representative",
    titleQanjobal: "Representante de Servicio al Cliente",
    companyName: "HelpDesk Pro",
    businessContactEmail: "careers@helpdeskpro.com",
    jobType: JobType.FULLTIME,
    acceptedLanguages: ["Non-English", "Spanish"],
    locationType: LocationType.REMOTE,
    city: "Miami",
    state: "Florida",
    url: "https://helpdeskpro.com/jobs/customer-service-rep-1",
    salary: 42000,
    expirationDate: new Date("2025-10-15"),
    descriptionEnglish:
      "Remote customer service position. Must be bilingual in English and Spanish. Full training provided.",
    descriptionQanjobal:
      "Mulnaj remoto yet' servicio al cliente. K'ulal bilingüe.",
    status: JobStatus.ACTIVE,
  },
  {
    titleEnglish: "Delivery Driver",
    titleQanjobal: "Conductor de Entregas",
    companyName: "QuickDeliver Express",
    businessContactEmail: "hiring@quickdeliver.com",
    jobType: JobType.FULLTIME,
    acceptedLanguages: ["Non-English", "Spanish", "Q'anjob'al"],
    locationType: LocationType.INPERSON,
    city: "Houston",
    state: "Texas",
    url: "https://quickdeliver.com/jobs/delivery-driver-9",
    salary: 40000,
    expirationDate: new Date("2025-11-20"),
    descriptionEnglish:
      "Delivery driver needed for local routes. Valid driver's license required. Flexible schedule.",
    descriptionQanjobal:
      "Conductor yet' entregas. Licencia válida k'ulal. Horario flexible.",
    status: JobStatus.ACTIVE,
  },
  {
    titleEnglish: "Retail Sales Associate",
    titleQanjobal: "Asociado de Ventas al Por Menor",
    companyName: "Fashion Forward",
    businessContactEmail: "jobs@fashionforward.com",
    jobType: JobType.PARTTIME,
    acceptedLanguages: ["Non-English", "Spanish"],
    locationType: LocationType.INPERSON,
    city: "New York",
    state: "New York",
    url: "https://fashionforward.com/careers/sales-associate-10",
    salary: 28000,
    expirationDate: new Date("2025-08-30"),
    descriptionEnglish:
      "Part-time retail position in downtown location. Weekend availability required.",
    descriptionQanjobal:
      "Mulnaj medio tiempo yet' ventas. Disponibilidad yet' fin de semana k'ulal.",
    status: JobStatus.ACTIVE,
  },
  {
    titleEnglish: "Administrative Assistant",
    titleQanjobal: "Asistente Administrativo",
    companyName: "Corporate Solutions Inc.",
    businessContactEmail: "hr@corpsolutions.com",
    jobType: JobType.FULLTIME,
    acceptedLanguages: ["Non-English"],
    locationType: LocationType.HYBRID,
    city: "Boston",
    state: "Massachusetts",
    url: "https://corpsolutions.com/jobs/admin-assistant-11",
    salary: 48000,
    expirationDate: new Date("2025-09-15"),
    descriptionEnglish:
      "Administrative assistant needed for busy office. Strong organizational skills required.",
    descriptionQanjobal:
      "Asistente administrativo yet' oficina ocupada. Habilidades organizacionales k'ulal.",
    status: JobStatus.ACTIVE,
  },
  {
    titleEnglish: "Landscaping Crew Member",
    titleQanjobal: "Miembro del Equipo de Jardinería",
    companyName: "GreenScape Landscaping",
    businessContactEmail: "jobs@greenscape.com",
    jobType: JobType.SEASONAL,
    acceptedLanguages: ["Non-English", "Spanish", "Q'anjob'al"],
    locationType: LocationType.INPERSON,
    city: "Portland",
    state: "Oregon",
    url: "https://greenscape.com/jobs/landscaping-crew-12",
    salary: 36000,
    expirationDate: new Date("2025-07-31"),
    descriptionEnglish:
      "Seasonal landscaping position. Experience preferred but will train. Outdoor work.",
    descriptionQanjobal:
      "Mulnaj temporal yet' jardinería. Experiencia preferida pero colonab'il.",
    status: JobStatus.ACTIVE,
  },
  {
    titleEnglish: "Medical Assistant",
    titleQanjobal: "Asistente Médico",
    companyName: "Community Health Clinic",
    businessContactEmail: "careers@communityhealthclinic.org",
    jobType: JobType.FULLTIME,
    acceptedLanguages: ["Non-English", "Spanish"],
    locationType: LocationType.INPERSON,
    city: "San Diego",
    state: "California",
    url: "https://communityhealthclinic.org/jobs/medical-assistant-13",
    salary: 44000,
    expirationDate: new Date("2025-10-30"),
    descriptionEnglish:
      "Medical assistant for community clinic. Certification preferred. Bilingual preferred.",
    descriptionQanjobal:
      "Asistente médico yet' clínica comunitaria. Certificación preferida.",
    status: JobStatus.ACTIVE,
  },
  {
    titleEnglish: "Night Shift Security Guard",
    titleQanjobal: "Guardia de Seguridad Turno Nocturno",
    companyName: "SecureWatch Security",
    businessContactEmail: "hiring@securewatch.com",
    jobType: JobType.FULLTIME,
    acceptedLanguages: ["Non-English", "Spanish"],
    locationType: LocationType.INPERSON,
    city: "Las Vegas",
    state: "Nevada",
    url: "https://securewatch.com/jobs/night-security-14",
    salary: 38000,
    expirationDate: new Date("2025-11-10"),
    descriptionEnglish:
      "Night shift security guard needed for commercial property. Clean background check required.",
    descriptionQanjobal:
      "Guardia de seguridad turno nocturno. Antecedentes limpios k'ulal.",
    status: JobStatus.ACTIVE,
  },
  {
    titleEnglish: "Cook/Chef",
    titleQanjobal: "Cocinero/Chef",
    companyName: "Bella Cucina Restaurant",
    businessContactEmail: "jobs@bellacucina.com",
    jobType: JobType.FULLTIME,
    acceptedLanguages: ["Non-English", "Spanish", "Q'anjob'al"],
    locationType: LocationType.INPERSON,
    city: "Chicago",
    state: "Illinois",
    url: "https://bellacucina.com/careers/cook-15",
    salary: 46000,
    expirationDate: new Date("2025-09-25"),
    descriptionEnglish:
      "Experienced cook needed for Italian restaurant. Evening shifts. Competitive pay.",
    descriptionQanjobal:
      "Cocinero con experiencia yet' restaurante italiano. Turnos yet' noche.",
    status: JobStatus.ACTIVE,
  },
  {
    titleEnglish: "Hotel Housekeeper",
    titleQanjobal: "Empleado de Limpieza de Hotel",
    companyName: "Grand Plaza Hotel",
    businessContactEmail: "hr@grandplazahotel.com",
    jobType: JobType.FULLTIME,
    acceptedLanguages: ["Non-English", "Spanish", "Q'anjob'al"],
    locationType: LocationType.INPERSON,
    city: "Orlando",
    state: "Florida",
    url: "https://grandplazahotel.com/jobs/housekeeper-16",
    salary: 32000,
    expirationDate: new Date("2025-08-20"),
    descriptionEnglish:
      "Housekeeper for busy hotel. Day shift available. Benefits included.",
    descriptionQanjobal:
      "Empleado de limpieza yet' hotel. Turno de día disponible. Beneficios incluidos.",
    status: JobStatus.ACTIVE,
  },
  {
    titleEnglish: "Childcare Provider",
    titleQanjobal: "Proveedor de Cuidado Infantil",
    companyName: "Little Stars Daycare",
    businessContactEmail: "careers@littlestarsdaycare.com",
    jobType: JobType.PARTTIME,
    acceptedLanguages: ["Non-English", "Spanish"],
    locationType: LocationType.INPERSON,
    city: "Denver",
    state: "Colorado",
    url: "https://littlestarsdaycare.com/jobs/childcare-provider-17",
    salary: 30000,
    expirationDate: new Date("2025-10-05"),
    descriptionEnglish:
      "Part-time childcare provider. Experience with young children required. CPR certification preferred.",
    descriptionQanjobal:
      "Proveedor de cuidado infantil medio tiempo. Experiencia con niños k'ulal.",
    status: JobStatus.ACTIVE,
  },
  {
    titleEnglish: "Factory Assembly Worker",
    titleQanjobal: "Trabajador de Ensamblaje de Fábrica",
    companyName: "Precision Manufacturing",
    businessContactEmail: "jobs@precisionmfg.com",
    jobType: JobType.FULLTIME,
    acceptedLanguages: ["Non-English", "Spanish", "Q'anjob'al"],
    locationType: LocationType.INPERSON,
    city: "Detroit",
    state: "Michigan",
    url: "https://precisionmfg.com/jobs/assembly-worker-18",
    salary: 42000,
    expirationDate: new Date("2025-12-15"),
    descriptionEnglish:
      "Assembly line worker for manufacturing facility. Multiple shifts available. Training provided.",
    descriptionQanjobal:
      "Trabajador de línea de ensamblaje. Múltiples turnos disponibles. Entrenamiento proporcionado.",
    status: JobStatus.ACTIVE,
  },
  {
    titleEnglish: "Pharmacy Technician Intern",
    titleQanjobal: "Practicante de Técnico de Farmacia",
    companyName: "HealthFirst Pharmacy",
    businessContactEmail: "internships@healthfirstpharmacy.com",
    jobType: JobType.INTERNSHIP,
    acceptedLanguages: ["Non-English", "Spanish"],
    locationType: LocationType.INPERSON,
    city: "Philadelphia",
    state: "Pennsylvania",
    url: "https://healthfirstpharmacy.com/jobs/pharm-tech-intern-19",
    salary: 22000,
    expirationDate: new Date("2025-06-15"),
    descriptionEnglish:
      "Pharmacy technician internship. Great opportunity for students pursuing pharmacy careers.",
    descriptionQanjobal:
      "Práctica de técnico de farmacia. Gran oportunidad yet' estudiantes.",
    status: JobStatus.ACTIVE,
  },
  {
    titleEnglish: "Freelance Translator",
    titleQanjobal: "Traductor Independiente",
    companyName: "Global Communications LLC",
    businessContactEmail: "projects@globalcomm.com",
    jobType: JobType.FREELANCE,
    acceptedLanguages: ["Non-English", "Spanish", "Q'anjob'al"],
    locationType: LocationType.REMOTE,
    city: "Remote",
    state: "Various",
    url: "https://globalcomm.com/freelance/translator-20",
    salary: 55000,
    expirationDate: new Date("2025-11-30"),
    descriptionEnglish:
      "Freelance translator for Spanish/Q'anjob'al to English. Flexible hours. Remote work.",
    descriptionQanjobal:
      "Traductor independiente. Horario flexible. Trabajo remoto.",
    status: JobStatus.ACTIVE,
  },
  {
    titleEnglish: "Janitorial Services",
    titleQanjobal: "Servicios de Conserjería",
    companyName: "Clean Pro Services",
    businessContactEmail: "hiring@cleanproservices.com",
    jobType: JobType.PARTTIME,
    acceptedLanguages: ["Non-English", "Spanish", "Q'anjob'al"],
    locationType: LocationType.INPERSON,
    city: "Atlanta",
    state: "Georgia",
    url: "https://cleanproservices.com/jobs/janitorial-21",
    salary: 26000,
    expirationDate: new Date("2025-07-15"),
    descriptionEnglish:
      "Part-time janitorial position for office buildings. Evening hours. No experience required.",
    descriptionQanjobal:
      "Mulnaj medio tiempo yet' conserjería. Horario nocturno. Sin experiencia necesaria.",
    status: JobStatus.ACTIVE,
  },
  {
    titleEnglish: "Personal Trainer",
    titleQanjobal: "Entrenador Personal",
    companyName: "FitLife Gym",
    businessContactEmail: "careers@fitlifegym.com",
    jobType: JobType.PARTTIME,
    acceptedLanguages: ["Non-English", "Spanish"],
    locationType: LocationType.INPERSON,
    city: "San Francisco",
    state: "California",
    url: "https://fitlifegym.com/jobs/personal-trainer-22",
    salary: 38000,
    expirationDate: new Date("2025-09-10"),
    descriptionEnglish:
      "Part-time personal trainer. Certification required. Flexible schedule.",
    descriptionQanjobal:
      "Entrenador personal medio tiempo. Certificación k'ulal. Horario flexible.",
    status: JobStatus.ACTIVE,
  },
  {
    titleEnglish: "Farm Worker",
    titleQanjobal: "Trabajador Agrícola",
    companyName: "Green Valley Farms",
    businessContactEmail: "jobs@greenvalleyfarms.com",
    jobType: JobType.SEASONAL,
    acceptedLanguages: ["Non-English", "Spanish", "Q'anjob'al"],
    locationType: LocationType.INPERSON,
    city: "Fresno",
    state: "California",
    url: "https://greenvalleyfarms.com/jobs/farm-worker-23",
    salary: 34000,
    expirationDate: new Date("2025-10-31"),
    descriptionEnglish:
      "Seasonal farm worker for harvest season. Housing provided. Experienced preferred.",
    descriptionQanjobal:
      "Trabajador agrícola temporal. Vivienda proporcionada. Experiencia preferida.",
    status: JobStatus.ARCHIVED,
  },
  {
    titleEnglish: "Sales Representative",
    titleQanjobal: "Representante de Ventas",
    companyName: "TechPro Solutions",
    businessContactEmail: "sales@techprosolutions.com",
    jobType: JobType.FULLTIME,
    acceptedLanguages: ["Non-English", "Spanish"],
    locationType: LocationType.HYBRID,
    city: "Dallas",
    state: "Texas",
    url: "https://techprosolutions.com/jobs/sales-rep-24",
    salary: 65000,
    expirationDate: new Date("2025-12-01"),
    descriptionEnglish:
      "B2B sales representative. Commission plus base salary. Company car provided.",
    descriptionQanjobal:
      "Representante de ventas B2B. Comisión más salario base. Carro de empresa proporcionado.",
    status: JobStatus.ACTIVE,
  },
  {
    titleEnglish: "Event Coordinator",
    titleQanjobal: "Coordinador de Eventos",
    companyName: "Premier Events Co.",
    businessContactEmail: "careers@premierevents.com",
    jobType: JobType.TEMPORARY,
    acceptedLanguages: ["Non-English", "Spanish"],
    locationType: LocationType.INPERSON,
    city: "Nashville",
    state: "Tennessee",
    url: "https://premierevents.com/jobs/event-coordinator-25",
    salary: 44000,
    expirationDate: new Date("2025-08-05"),
    descriptionEnglish:
      "Temporary event coordinator for summer season. Event planning experience required.",
    descriptionQanjobal:
      "Coordinador de eventos temporal. Experiencia en planificación k'ulal.",
    status: JobStatus.ARCHIVED,
  },
];
