name: Check

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  mobile-app-format:
    runs-on: ubuntu-latest
    name: Mobile App Format
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: mobile-app/package-lock.json

      - name: Install dependencies
        working-directory: ./mobile-app
        run: npm i

      - name: Check formatting
        working-directory: ./mobile-app
        run: npx expo lint

  # mobile-app-build:
  #   runs-on: ubuntu-latest
  #   name: Mobile App Build
  #   steps:
  #     - name: Check out repository
  #       uses: actions/checkout@v2

  #     - name: Set up Node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #         cache: 'npm'
  #         cache-dependency-path: mobile-app/package-lock.json

  #     - name: Install dependencies
  #       working-directory: ./mobile-app
  #       run: npm i

  #     - name: Run build
  #       working-directory: ./mobile-app
  #       run: npx expo export

  admin-dashboard-format:
    runs-on: ubuntu-latest
    name: Admin Dashboard Format
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: admin-dashboard/package-lock.json

      - name: Install dependencies
        working-directory: ./admin-dashboard
        run: npm i

      - name: Check formatting
        working-directory: ./admin-dashboard
        run: npm run format:check

  admin-dashboard-build:
    runs-on: ubuntu-latest
    name: Admin Dashboard Build
    environment: Production
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: admin-dashboard/package-lock.json

      - name: Install dependencies
        working-directory: ./admin-dashboard
        run: npm i

      - name: Run build
        working-directory: ./admin-dashboard
        env:
          JILA_BACKEND_PRISMA_DATABASE_URL: ${{ secrets.JILA_BACKEND_PRISMA_DATABASE_URL }}
          JILA_BACKEND_POSTGRES_URL: ${{ secrets.JILA_BACKEND_POSTGRES_URL }}
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
        run: npm run build