name: Check

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  frontend-format:
    runs-on: ubuntu-latest
    name: Frontend Format
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./frontend
        run: npm i

      - name: Check formatting
        working-directory: ./frontend
        run: npx expo lint

  frontend-build:
    runs-on: ubuntu-latest
    name: Frontend Build
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./frontend
        run: npm i

      - name: Run build
        working-directory: ./frontend
        run: npx expo export

  backend-format:
    runs-on: ubuntu-latest
    name: Backend Format
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        working-directory: ./backend
        run: npm i

      - name: Check formatting
        working-directory: ./backend
        run: npm run format:check

  backend-build:
    runs-on: ubuntu-latest
    name: Backend Build
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        working-directory: ./backend
        run: npm i

      - name: Run build
        working-directory: ./backend
        env:
          JILA_BACKEND_PRISMA_DATABASE_URL: ${{ secrets.JILA_BACKEND_PRISMA_DATABASE_URL }}
          JILA_BACKEND_POSTGRES_URL: ${{ secrets.JILA_BACKEND_POSTGRES_URL }}
        run: npm run build